# -*- coding: utf-8 -*-
"""convert_bmp_to_jpg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oZuIgSQQodLcApwFszhSg6uJ0ITnga84
"""

"""
Script to convert .bmp image files into .jpg files
"""

from PIL import Image
import os

# Update file path for images and masks alike
input_folder = '/content/rooftop/masks'
output_folder = '/content/rooftop/masks/png/'

# If output folder does not exist, create new folder
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Loop through all files in the input folder
for filename in os.listdir(input_folder):
    # Search for .bmp files
    if filename.endswith('.bmp'):
        # Open the .bmp file
        with Image.open(os.path.join(input_folder, filename)) as img:
            # Remove the .bmp extension and add .jpg extension for the output file
            output_filename = os.path.splitext(filename)[0] + '.jpg'
            # Save the image as .jpg in the output folder
            img.save(os.path.join(output_folder, output_filename), 'JPEG')

print("Conversion complete.")